# ============================================================
# ACG-Faka 独立版 v2.0 - 宝塔伪静态规则
# ============================================================

location / {
    if (!-e $request_filename){
        rewrite ^(.*)$ /index.php?s=$1 last;
    }
}

# 禁止访问敏感文件
location ~* (runtime|application|kernel|config)/.*\.php$ {
    deny all;
}

# 禁止访问隐藏文件
location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
}
